wip save 25

diff --git a/snmp_test_mib b/snmp_test_mib
--- a/snmp_test_mib
+++ b/snmp_test_mib
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-GET=no
-WALK=no
-TRAP=no
-
 IPv4=yes
-IPv6=yes
-DTLSUDP4=yes
-DTLSUDP6=yes
-TCPDUMP=yes
+IPv6=no
+DTLSUDP4=no
+DTLSUDP6=no
+TCPDUMP=no
+
 [ -z "$REMOTE" ] && REMOTE=no
 [ -z "$REMOTE_TCPDUMP" ] && REMOTE_TCPDUMP=no
 SNMP_PROTOCOL="3"
@@ -68,6 +65,7 @@ IPv4_HOST=0.0.0.0
 IPv4_LO=127.0.0.1
 IPv4_EXTRA=172.16.1.100
 IPv4_DEV0=$(ip -o -4 addr list $IPDEV0 | head -1 | awk '{print $4}' | cut -d/ -f1)
+IPv4_DEV0_LAST=$(echo $IPv4_DEV0 | cut -d'.' -f4)
 
 IPv6_HOST=::
 IPv6_LO=::1
@@ -154,7 +152,7 @@ function prepare_ip () {
     IPv6_DEV0=$(ip -o -6 addr list $IPDEV0 | grep global | head -1 | awk '{print $4}' | cut -d/ -f1)
     if [ -z $IPv6_DEV0 ]; then
 	# set global IPv6
-	IPv6_DEV0=2001:1b70:82a8:90:1284:31:0:182
+	IPv6_DEV0=2001:1b70:82a8:90:1284:31:0:${IPv4_DEV0_LAST}
 	ifconfig $IPDEV0 inet6 add $IPv6_DEV0/80
     fi
 
@@ -236,18 +234,18 @@ function create_snmpd_conf ()
 
     if [ "$IPv4" == "yes" ]; then
 	if [ $SNMP_PROTOCOL == "3" ]; then
-	    #echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp:$IPv4_DEV0:$SNMPTRAPD_PORT" >> $conf
-	    echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp:$REMOTE_IPv4:$SNMPTRAPD_PORT" >> $conf
+	    echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp:$IPv4_DEV0:$SNMPTRAPD_PORT" >> $conf
+	    #echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp:$REMOTE_IPv4:$SNMPTRAPD_PORT" >> $conf
 	elif [ $SNMP_PROTOCOL == "2c" ]; then
 	    echo "trap2sink udp:$IPv4_LO:$SNMPTRAPD_PORT" >> $conf
 	    echo "trap2sink udp:$REMOTE_IPv4:$SNMPTRAPD_PORT" >> $conf
 	fi
     fi
 
-    if [ "$IPv6" == "NO" ]; then
+    if [ "$IPv6" == "yes" ]; then
 	if [ $SNMP_PROTOCOL == "3" ]; then
 	    echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp6:$IPv6_DEV0:$SNMPTRAPD_PORT" >> $conf
-	    echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp6:$REMOTE_IPv6:$SNMPTRAPD_PORT" >> $conf
+	    #echo "trapsess -v 3 -e $USM_EID -a MD5 -A $USM_PW -x AES -X $USM_PW -l authPriv -u $USM_USER udp6:$REMOTE_IPv6:$SNMPTRAPD_PORT" >> $conf
 	elif [ $SNMP_PROTOCOL == "2c" ]; then
 	    echo "trap2sink udp6:[$IPv6_LO]:$SNMPTRAPD_PORT" >> $conf
 	    echo "trap2sink udp6:[$REMOTE_IPv6]:$SNMPTRAPD_PORT" >> $conf
@@ -260,13 +258,13 @@ function create_snmpd_conf ()
 	echo "certSecName 10 $appCert --cn" >> $conf
 	echo "rwuser -s tsm $TSM_USER authpriv" >> $conf
 
-	if [ "$DTLSUDP4" == "NO" ]; then
+	if [ "$DTLSUDP4" == "yes" ]; then
 	    echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtlsudp:$IPv4_DEV0:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
-	    echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtlsudp:$REMOTE_IPv4:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
+	    #echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtlsudp:$REMOTE_IPv4:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
 	fi
 	if [ "$DTLSUDP6" == "yes" ]; then
-	    #echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtlsudp6:[$IPv6_DEV0]:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
-	    echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtls:[$REMOTE_IPv6]:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
+	    echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtlsudp6:[$IPv6_DEV0]:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
+	    #echo "trapsess -v 3 -T localCert=$appCert -T peerCert=$serverCert dtls:[$REMOTE_IPv6]:$SNMPTRAPD_DTLSUDP_PORT" >> $conf
 	fi
     fi
 }
@@ -475,48 +473,93 @@ function tcpdump_read ()
     fi
 }
 
-function configure_mib()
+function convert_ip2hex ()
 {
     local host=$1
-    local obj="\'mytrap\'"
+    local port=$2
 
-    echo "##### !!!!!! NOT WORKING YET, some missing configuration......!!!!!"
-    
+    printf "0x"
+    echo $host | grep : >/dev/null
+    if [ $? = 0 ]; then
+	# IPv6
+	for i in $(echo $host | tr ':' ' '); do
+	    printf "%04x" $(echo $((16#$i)))
+	done
+    else
+	# IPv4
+	for i in $(echo $host | tr '.' ' '); do
+	    printf "%02x" $i
+	done
+    fi
+    printf "%04x" $port
+    printf "\n"
+}
+
+function configure_mib_dtlsudp()
+{
+    local host=$1
+    local targetaddr=$(convert_ip2hex $2 $3)
+    local obj="'mytrap'"
+    local link=internal0
+    local proto=udp
+
+    echo -e "\n##### !!!!!! NOT WORKING YET, some missing configuration......!!!!!\n"
+
     echo $host | grep dtlsudp >/dev/null
     if [ "$?" -eq 0 ]; then
 	# TSM
-	echo TBD
-	$BASH "snmpset -v 3 --defSecurityModel=tsm $host TBD"
+	proto=dtlsudp
+	local SNMPSET="snmpset -v 3 --defSecurityModel=tsm $host TBD"
     else
 	# USM
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrRowStatus.$obj = 5"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrTimeout.$obj = 100"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrRetryCount.$obj = 5"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrTagList.$obj = mytrap"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrParams.$obj = mytrap"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrStorageType.$obj = 3"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMP-TLS-TM-MIB::snmpDTLSUDPDomain"
-	#local eth0 = "20 01 0D B8 00 02 00 00 00 00 00 00 00 00 00 03 27 B2"
-	#local eth1 = "20 01 0D B8 00 03 00 00 00 00 00 00 00 00 00 03 27 B2"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrTAddress.$obj = \"20 01 0D B8 00 03 00 00 00 00 00 00 00 00 00 03 27 B2\""
-
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsRowStatus.$obj = 5"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsStorageType.$obj = 3"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsMPModel.$obj = 3"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsSecurityModel.$obj = 4"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsSecurityName.$obj = whatever"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsSecurityLevel.$obj = 3"
-
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-NOTIFICATION-MIB::snmpNotifyRowStatus.$obj = 5"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-NOTIFICATION-MIB::snmpNotifyTag.$obj = mytrap"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-NOTIFICATION-MIB::snmpNotifyType.$obj = 1"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-NOTIFICATION-MIB::snmpNotifyStorageType.$obj = 3"
-
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetAddrRowStatus.$obj = 1"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-TARGET-MIB::snmpTargetParamsRowStatus.$obj = 1"
-	$BASH "snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host SNMP-NOTIFICATION-MIB::snmpNotifyRowStatus.$obj = 1"
+	local SNMPSET="snmpset -v 3 -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host"
+	echo $host | grep udp6 >/dev/null
+	if [ "$?" -eq 0 ]; then
+	    proto=udp6
+	fi
     fi
 
+    # snmpNotify
+    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyRowStatus.$obj = 5
+    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyTag.$obj = $link
+    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyType.$obj = 1
+    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyStorageType.$obj = 3
+
+    # snmpTargetParams
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsRowStatus.$obj = 5
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsStorageType.$obj = 3
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsMPModel.$obj = 3
+    if [ $proto = dtlsudp ]; then
+	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityModel.$obj = 4
+	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityName.$obj = should_be_set_to_something
+    else
+	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityModel.$obj = 3
+	$SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityName.$obj = usmuser
+    fi
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsSecurityLevel.$obj = 3
+
+    # snmpTargetAddr
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrRowStatus.$obj = 5
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTimeout.$obj = 100
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrRetryCount.$obj = 5
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTagList.$obj = $link
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrParams.$obj = $link
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrStorageType.$obj = 3
+    if [ $proto = dtlsudp ]; then
+       $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMP-TLS-TM-MIB::snmpDTLSUDPDomain
+    fi
+    if [ $proto = udp6 ]; then
+	$SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMPv2-SMI::mib-2.100.1.2
+    fi
+    if [ $proto = udp ]; then
+	$SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTDomain.$obj = SNMPv2-TM::snmpUDPDomain
+    fi
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrTAddress.$obj x $targetaddr
+
+    # enable the trap?
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetAddrRowStatus.$obj = 1
+    $SNMPSET SNMP-TARGET-MIB::snmpTargetParamsRowStatus.$obj = 1
+    $SNMPSET SNMP-NOTIFICATION-MIB::snmpNotifyRowStatus.$obj = 1
 }
 
 function get_mib()
@@ -526,7 +569,7 @@ function get_mib()
 
     $NOTE $FUNCNAME $host
 
-    for oid in $oids; do 
+    for oid in $oids; do
 	echo $host | grep dtlsudp >/dev/null
 	if [ "$?" -eq 0 ]; then
 	    $BASH "snmpbulkwalk -v $SNMP_PROTOCOL --defSecurityModel=tsm $host $oid"
@@ -534,6 +577,7 @@ function get_mib()
 	    $BASH "snmpbulkwalk -v $SNMP_PROTOCOL -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host $oid"
 	fi
     done
+    #$BASH "snmpbulkwalk -v $SNMP_PROTOCOL -a MD5 -A $USM_PW -l authNoPriv -u $USM_USER $host . > $SNMPWALK_OUT"
     #sleep 2
     #grep 'SNMP-TARGET-MIB\|SNMP-NOTIFICATION-MIB' $SNMPWALK_OUT
 }
@@ -592,8 +636,27 @@ prepare
 set_servers
 snmp_start
 
-configure_mib udp6:[$IPv6_HOST]:$SNMPD_PORT
-get_mib udp6:[$IPv6_HOST]:$SNMPD_PORT
+CONFIG_HOST=$IPv4_HOST:$SNMPD_PORT
+#CONFIG_HOST=udp6:[$IPv6_HOST]:$SNMPD_PORT
+#CONFIG_HOST=dtlsudp:$IPv4_HOST:$SNMPD_PORT
+#CONFIG_HOST=dtlsudp6:[$IPv6_HOST]:$SNMPD_PORT
+
+CONFIG_IPv4=$IPv4_DEV0
+CONFIG_IPv6=$IPv6_DEV0
+
+if [ "$IPv4" == "yes" ]; then
+    configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv4 $SNMPTRAPD_PORT
+fi
+if [ "$IPv6" == "yes" ]; then
+    configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv6 $SNMPTRAPD_PORT
+fi
+if [ "$DTLSUDP4" == "yes" ]; then
+    configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv4 $SNMPTRAPD_DTLSUDP_PORT
+fi
+if [ "$DTLSUDP6" == "yes" ]; then
+    configure_mib_dtlsudp $CONFIG_HOST $CONFIG_IPv6 $SNMPTRAPD_DTLSUDP_PORT
+fi
+get_mib $CONFIG_HOST
 
 if [ "$TCPDUMP" == "yes" ]; then
     $NOTE capture tcpdump for traps
